version: '3'
services:
  freeswitch:
    image: drachtio/freeswitch:latest
    ports:
      - "5080:5060/udp"
      - "8021:8021"
    volumes:
      - ./freeswitch-config:/etc/freeswitch
    networks:
      - restaurant-net
  
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./service.json:/app/service.json
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      - CARTESIA_VOICE_ID=${CARTESIA_VOICE_ID}
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/service.json
    networks:
      - restaurant-net
    command: python main.py

  # Menu management service
  menu-seeder:
    build: .
    volumes:
      - .:/app
      - ./service.json:/app/service.json
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/service.json
    networks:
      - restaurant-net
    profiles:
      - tools
    command: python scripts/quick_seed.py

networks:
  restaurant-net:
    driver: bridge
