apiVersion: v1
kind: Service
metadata:
  name: livekit-service
  namespace: vocare-restaurant
  labels:
    app: livekit-server
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-external-subnet: "default"
spec:
  selector:
    app: livekit-server
  ports:
  - name: websocket
    port: 7880
    targetPort: 7880
    protocol: TCP
  - name: websocket-tls
    port: 7881
    targetPort: 7881
    protocol: TCP
  - name: turn-udp
    port: 7882
    targetPort: 7882
    protocol: UDP
  type: LoadBalancer

---
# Internal service for cluster communication
apiVersion: v1
kind: Service
metadata:
  name: livekit-internal
  namespace: vocare-restaurant
  labels:
    app: livekit-server
spec:
  selector:
    app: livekit-server
  ports:
  - name: websocket
    port: 7880
    targetPort: 7880
    protocol: TCP
  type: ClusterIP