# Service Account for Azure Workload Identity
# This enables secure access to Azure Key Vault without storing credentials

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vocare-workload-identity
  namespace: vocare-restaurant
  annotations:
    azure.workload.identity/client-id: "f5bab3ac-2bf5-42a1-a7c1-b061d112e935"
  labels:
    azure.workload.identity/use: "true"

---
# ClusterRole for accessing secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vocare-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vocare-secret-reader-binding
subjects:
- kind: ServiceAccount
  name: vocare-workload-identity
  namespace: vocare-restaurant
roleRef:
  kind: ClusterRole
  name: vocare-secret-reader
  apiGroup: rbac.authorization.k8s.io