apiVersion: v2
name: vocare-restaurant
description: A Helm chart for Vocare Restaurant AI Assistant with SIP telephony support
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ai
  - restaurant
  - telephony
  - livekit
  - freeswitch
home: https://github.com/yourusername/vocare
sources:
  - https://github.com/yourusername/vocare
maintainers:
  - name: Your Name
    email: your-email@example.com
dependencies: []