# Azure Key Vault Secret Provider Class for Vocare Restaurant Assistant
# This integrates Azure Key Vault with AKS for secure secret management

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vocare-keyvault-secrets
  namespace: vocare-restaurant
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "f5bab3ac-2bf5-42a1-a7c1-b061d112e935"  
    keyvaultName: "vocare-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: openai-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: deepgram-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: cartesia-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: livekit-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: livekit-api-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: sip-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: sip-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: sip-realm
          objectType: secret
          objectVersion: ""
        - |
          objectName: sip-proxy
          objectType: secret
          objectVersion: ""
        - |
          objectName: freeswitch-default-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: firebase-service-account-json
          objectType: secret
          objectVersion: ""
    tenantId: "eca68c78-3e63-4c2b-bbf0-e41455a7ff01"
  secretObjects:
  - secretName: vocare-api-secrets
    type: Opaque
    data:
    - objectName: openai-api-key
      key: openai-api-key
    - objectName: deepgram-api-key
      key: deepgram-api-key
    - objectName: cartesia-api-key
      key: cartesia-api-key
    - objectName: livekit-api-key
      key: livekit-api-key
    - objectName: livekit-api-secret
      key: livekit-api-secret
  - secretName: vocare-sip-secrets
    type: Opaque
    data:
    - objectName: sip-username
      key: sip-username
    - objectName: sip-password
      key: sip-password
    - objectName: sip-realm
      key: sip-realm
    - objectName: sip-proxy
      key: sip-proxy
  - secretName: vocare-freeswitch-secrets
    type: Opaque
    data:
    - objectName: freeswitch-default-password
      key: default-password
  - secretName: vocare-firebase-secret
    type: Opaque
    data:
    - objectName: firebase-service-account-json
      key: service-account-json